### PR TITLE
Reducing AEAD expansion to a maximum of 256 bytes

### LINKED ISSUE #55: Reduce the "overhead" values in TLSCiphertext, etc.
This is currently 2^{14} + 2048 (in TLSCiphertexT) and then 2^{14} + 1024 later.

This is introduced by leaving room for compression. Should we just reduce this entirely across the board. Certainly we don't need to leave room for compression.

### PR DESCRIPTION
**Pull request by martinthomson**
As discussed on list.

Closes #55.

### CODE REVIEW

**Comment by davegarrett** [comment]
Minor suggestions:

1) Explicitly specify the expectation of a "record_overflow" alert after the two "MUST NOT"s.
2) Also drop the issue #55 "OPEN ISSUE" note that's on line 1087-1088.
3) Amend the changelog to mention this.
4) Add a sentence noting the overhead cap has changed to the "Note: In versions of TLS prior to 1.3" paragraph, or elsewhere.

**Comment by martinthomson** [comment]
As @davegarrett suggests, I've updated the PR.  I have not added the Note.  I don't like those.  The change log is enough.

**Comment by davegarrett** [comment]
Why was the changelog amended as for draft-09? The draft-08 hasn't been published yet. Is it in the progress of being released? (not shown on DataTracker and releases haven't been tagged on GitHub since draft-05)

**Comment by ekr** [comment]
Pilot error. Please feel free to submit a PR.

**Pull request merged**
