### PR TITLE
update reference for RFC7627 & linkify RFC4492 author notes

### PR DESCRIPTION
**Pull request by davegarrett**

### CODE REVIEW

**Comment by davegarrett** [comment]
Travis fails because it doesn't know about the new RFC yet. I don't know what's needed to fix that.

**Comment by ekr** [comment]
@martinthomson can you update our local copy of the rfc bib?

**Comment by martinthomson** [comment]
Updated.  You should poke travis again.

**Comment by ekr** [comment]
I'm just going to assume this is cool and merge.

**Pull request merged**
