### PR TITLE
a big pile of minor fixes

### PR DESCRIPTION
**Pull request by davegarrett**
Capitalize the first letter of the sentence like the rest of the alert descriptions.

### CODE REVIEW

**Comment by davegarrett** [comment]
I just noticed that @seanturner noticed this too and included it in PR #153 with quite a few more significant editorial improvements around alerts.

**Comment by davegarrett** [comment]
Rather than creating new PRs, I've just added a couple other minor things to this one.

**Comment by davegarrett** [comment]
I've just added to this two almost identical looking commits to upgrade the HTTP links to HTTPS in README.md and CONTRIBUTING.md. Can CONTRIBUTING.md just be deleted, or is it still needed for some reason?

**Comment by martinthomson** [comment]
CONTRIBUTING.md is needed to generate the banner that you see.

I see no harm in including a link to CONTRIBUTING.md from README.md if you want to do that.

**Comment by davegarrett** [comment]
Transclusion would be ideal, if that capability exists. I don't think changing it to just a link is needed. As long as they're both being used and both updated as-needed, I have nothing against just duplicating the content. Just checking to make sure.

**Comment by davegarrett** [comment]
Huh. Looks like I've found the most pedantic errata ever: it says "see page 99" when it should've said "see page 100" in the TLS 1.2 spec. The most recent trivial fix in this PR changes that to an actual link to the section in question. I would guess it's not worth actually filing an errata ticket for that. ;)

**Pull request merged**
