### PR TITLE
 Reusing psk identities enables client and server tracking

### PR DESCRIPTION
**Pull request by emanjon**
#1287

### CODE REVIEW

**Comment by emanjon** [comment]
#1289
Added server tracking by changing the heading. The rest of the text talks about connections and therefore apply to both client and server tracking.

**Review by kaduk — COMMENTED** [review]
If we're going to strongly disrecommend (SHOULD NOT is essentially "MUST NOT unless you have a good excuse), we should probably have some plausible, generic, strategy for an alternative.  For connections that use actual pre-shared keys, how might you propose that they produce non-reused psk identifiers when the actual shared key does not change?

**Comment by martinthomson** [comment]
A PSK identifier could be a nonce (random), plus an encryption of the true identifier, using that nonce as input to the key derivation process.  There are options for similar protections that use something like FPE (such as [this](https://quicwg.org/load-balancers/draft-ietf-quic-load-balancers.html#section-4)), but they might not be strong enough to pass serious scrutiny as a generic mechanism.

**Comment by ekr** [comment]
I agree that this is a real issue but I also think that the SHOULD NOT is too strong given the state of the art. I don't really think that a SHOULD NOT is that great. PR #1294 takes a more descriptive approach.

**Comment by ekr** [comment]
I am closing based on PR #1294.

**Pull request closed without merging**
