### PR TITLE
Sean's fixes pile, take 3

### PR DESCRIPTION
**Pull request by davegarrett**
This replaces PR #152 and https://github.com/ekr/tls13-spec/tree/seanturner_protocol_capitalization

After @ekr landed the recent draft 7 overhaul, @seanturner's fixes branch was heavily bitrotted again. I suggested ekr review and merge it recently, but I went over it again earlier and I don't think that's viable as-is anymore. I'm not a git pro, but I think I've managed to deconflict this again to the point where it's usable. I squashed a lot of commits on the same days together as this made it much easier for me to resolve the conflicts. (also got rid of some commits & reversions) This doesn't have ekr's deconflict commit in there or a deconflict commit from myself for this round, but I don't think that's too important. I also fixed a typo in one of the reference links in there somewhere. There's a lot of little things in here, but there's also a few important ones (e.g. first change updates FIPS ref), so I think this is important to finally get fixed up and merged.

@seanturner: Please review this and make sure all of your stuff made it through to here ok. (at least the changes that weren't completely superseded by ekr's big commit) I think there's probably a few peers/parties bits that could be added/redone, but I don't think anything major got lost.

One important change to review: "supported_groups" was renamed to "named_groups". Did we want to keep the old name or merge this change? If not, one of us can revert that part.

### CODE REVIEW

**Comment by davegarrett** [comment]
I also managed to fix the author metadata for these commits to actually be for the correct account. All the commits in the old PR & branches had a different email address listed and confused GitHub. (the old commits had no icons on here; these amalgamated commits are cited as from Sean's account properly)

**Comment by seanturner** [comment]
FYI - I�m perfectly happy that you tweaked/fixed this Dave.

spt

**Comment by ekr** [comment]
This looks good but needs a rebase. Can you do that?

**Comment by davegarrett** [comment]
Yay, more rebasing. :p
Sure, gimmie a sec and I'll do that.

**Comment by davegarrett** [comment]
Rebased.

**Pull request merged**
