### PR TITLE
Alert clarifications

### PR DESCRIPTION
**Pull request by tomato42**
Fix few typos and clarify when and if alerts should be sent.

### CODE REVIEW

**Comment by ekr** [comment]
This PR does not match the WG consensus which is that sending alerts was optional

**Comment by tomato42** [comment]
But it does say that sending alerts is optional, it just explains why its not good thing to do: https://github.com/tlswg/tls13-spec/pull/703/files#diff-9d84740dcc569a0a5a359d0fba461a05R3656

**Comment by ekr** [comment]
See above.

**Comment by tomato42** [comment]
new line 3656 clearly states that not sending alerts is acceptable, the patches do not modify the existing text in line 3632/3645

so which line nullifies this?

**Comment by ekr** [comment]
The line where you removed the word "optional"

**Comment by tomato42** [comment]
That is general description of the protocol, there are no RFC 2119 keywords there. The whole section is very low on details

I don't see how that overrides the text in line 3622/364:

>  Whenever an implementation encounters a fatal error condition, it
> SHOULD send an appropriate fatal alert and MUST close the connection
> without sending or receiving any additional data.

text which  the patches don't modify

**Comment by ekr** [comment]
I took the parts of this that I think are useful improvements. I don't think that the text exhorting people harder to send alerts helps and that the alerts to send in the cases of fragment errors are clear enough already.

**Pull request closed without merging**
