### PR TITLE
Proposal to change session ticket lifetime

### PR DESCRIPTION
**Pull request by grittygrease**
Change ticket_lifetime_hint to ticket_lifetime and add stricter requirements.

### CODE REVIEW

**Comment by martinthomson** [comment]
lgtm

Please send an email to tls@ietf.org pointing to the change and making a case for it.

**Comment by grittygrease** [comment]
Sent, thanks.

**Comment by grittygrease** [comment]
Mailing list discussion here:
https://www.ietf.org/mail-archive/web/tls/current/msg19283.html

**Comment by siyengar** [comment]
+1

**Comment by ekr** [comment]
Merging per WG discussion.

@grittygrease please send me a PR adding yourself to acknowledgements :)

**Pull request merged**
