### PR TITLE
Add data volume limits

### PR DESCRIPTION
**Pull request by ekr**

### CODE REVIEW

**Comment by ekr** [comment]
@wbl PTAL

**Comment by wbl** [comment]
Looks like it accurately represents the citation, which I remember previously checking for correctness.

**Comment by ekr** [comment]
Thanks!

**Comment by ekr** [comment]
@kennypaterson comments?

**Comment by ekr** [comment]
Merged separately.

**Comment by kennypaterson** [comment]
This "data limits" text is good. We need to spell Atul's name properly though - it's Atul Luykx.

Additionally, it might be good to mention that the actual data limits are predicated on the assumption that the underlying PRF has no weaknesses (this being AES for AES-GCM and ChaCha20 for ChaCha20-Poly1305).

**Comment by ekr** [comment]
See:
https://github.com/tlswg/tls13-spec/commit/42edc9b79e80e415fe60cd55ff704d77fe993a0f

**Pull request closed without merging**
