### PR TITLE
mention (EC)DHE+PSK (issue #309)

### PR DESCRIPTION
**Pull request by davegarrett**
Quick PR for proposed change for issue #309.

### CODE REVIEW

**Comment by ekr** [comment]
Actually, looking at this again, this proposal is not really what's wanted here.

The natural case here is that the client will offer only:
Sig + ECDHE (full handshake) and PSK (resumption)

**Comment by davegarrett** [comment]
I thought we were using (EC)DHE+PSK for resumption? I mentioned previously that I think plain PSK for resumption is appropriate, but I vaguely remember someone saying we were going to use PFS+PSK here anyway. I don't see a reason to not support it, though.

**Comment by ekr** [comment]
The client can use either plain PSK or (EC)DHE+PSK for resumption, at its discretion (this is one of the advantages of a more decoupled design). However, the natural counterpart is pure PSK.

**Comment by davegarrett** [comment]
Well, if you think the current text is preferred, I have no objection to just closing this and the issue.

The PSK resumption story really does need to be clarified as to explicitly how offer and negotiate which cipher suites, by the way.

**Comment by ekr** [comment]
I don't think this is what's needed.

**Pull request closed without merging**
