### PR TITLE
very trivial fixes

### PR DESCRIPTION
**Pull request by davegarrett**
Consistently capitalize AEAD, fix a missing period, and fix a typo in a comment (for the sole purpose of appeasing my perfectionist tendencies ;).

### CODE REVIEW

**Comment by ekr** [comment]
I don't think changing aead-ciphered to AEAD-ciphered in the protocol description is an improvement.

The typo fix is good :)

**Comment by davegarrett** [comment]
3 lines below aead-ciphered we have TLSCiphertext. Abbreviations are already kept in caps in almost every place. I don't see why it shouldn't be consistent and do so here as well.

**Comment by ekr** [comment]
I'd prefer to stay consistent with TLS 1.2.

**Comment by davegarrett** [comment]
Meh, ok. It looks out of place to me, but it's not a big deal. Commit revised to just fix the missing period and typo.

**Pull request merged**
