### PR TITLE
removed empty cases for EarlyDataIndication presentation language

### PR DESCRIPTION
**Pull request by mimoo**
removing confusing cases syntax after https://github.com/tlswg/tls13-spec/issues/861 discussion

### CODE REVIEW

**Comment by kaduk** [comment]
I don't think this is correct -- we need to specify the structure that is sent in the body of this extension when carried in those messages; it just happens to be an empty structure.

**Comment by mimoo** [comment]
I'm not sure how you would read that differently. An empty structure would be the same as no case

**Comment by kaduk** [comment]
Well, we do say "The selector must be an enumerated type that defines the possible variants the structure defines. There must be a case arm for every element of the enumeration declared in the select."  So my claim would be more that it is invalid to have a select(Handshake.msg_type) that does not include a case arm for a message type that is allowed to contain this extension.

**Comment by mimoo** [comment]
Ah I see! I missed that.

**Pull request closed without merging**
