### PR TITLE
EndOfEarlyData comes after ServerFinished

### PR DESCRIPTION
**Pull request by kaduk**
Remove redundant bits in the table of base key computations.

### CODE REVIEW

**Comment by davidben** [comment]
"Later of" is a slightly odd phrasing, but I think it's written this way because EndOfEarlyData isn't always present. Similar with "later of EncryptedExtensions/CertificateRequest".

**Comment by davegarrett** [comment]
Yes, I think this is correct as-is.

**Comment by ekr** [comment]
I also think this is correct.

@kaduk: objections to closing this?

**Comment by kaduk** [comment]
No real objection, though it sort of seems like there is room for increased clarity here.
I just filed this because I made an observation in a posting on the list and didn't want it to get lost.

**Pull request closed without merging**
