### PR TITLE
Fix alert names when referred to

### PR DESCRIPTION
**Pull request by beurdouche**
Sometimes the alert name is in between quotes like : "protocol_version" alert ..
and sometimes it is not ... like : close_notify alert

### CODE REVIEW

**Comment by beurdouche** [comment]
There is something else that should be fixed ...
Sometimes the alert name is in between quotes like "protocol_version" alert ..
and sometimes it is not like : close_notify 

I could make all that uniform with or without quotes.
my preference goes to adding quotes around all ...

**Comment by beurdouche** [comment]
I made all alert names citations consistent across the text by adding quotes when missing
B.

**Comment by beurdouche** [comment]
First commit : 
fix typos

Second commit :
I made all alert names citations consistent across the text by adding quotes when missing

B.

**Comment by seanturner** [comment]
BTW - I noted the same inconsistencies.

**Pull request merged**
