### PR TITLE
Explicitly specify SSLv2/SSLv3

### PR DESCRIPTION
**Pull request by yuhong**
Explicitly specify SSL version 2 and SSL version 3.

### CODE REVIEW

**Comment by davegarrett** [comment]
I don't think this is a helpful change. That list is long enough already.

"SSL" necessarily includes SSL 1-3. Dropping SSL2 compatible CLIENT-HELLO support is recommended, so it doesn't need singling out separately as permitted. Also, supporting it is not support for SSL2; it's an obsolete compatibility shim for TLS, so that's not even covered here. Implementations can support both TLS & SSL2 CLIENT-HELLO, but not SSL, just fine.

**Comment by yuhong** [comment]
"SSL" is often used to refer to all SSL/TLS versions.

**Comment by davegarrett** [comment]
And that practice needs to stop.

If this was anywhere other than directly in the TLS specification itself, I might agree with you with a need for clarification. However, it's clearly not telling people to make sure not to implement itself. ;)

**Comment by davegarrett** [comment]
If @ekr agrees with enumerating it to "SSL 2.0, SSL 3.0", instead of simply "SSL", I don't think it's needed but I don't object.

The SSL2 compatible CLIENT-HELLO parenthetical, however, is not relevant here as that's a shim for TLS, not SSL2 support itself, and I'd like to keep mention of it as banished as possible. Implementations are permitted to drop support for it, but it's only a recommendation.

Note that we previously had a mix of "SSL3", "SSLv3", and "SSL 3.0" all scattered about, which made things a bit inconsistent and annoying to search the document for. I normalized all mentions of versions to use the "SSL 3.0" style version notation a while back, so please use this notation.

**Comment by ekr** [comment]
I agree with @davegarrett, this isn't really making things clearer.

**Comment by yuhong** [comment]
Also, TLS 1.0 was far less different from SSL 3.0 than SSL 3.0 was against SSL 2.0.

**Pull request closed without merging**
