### PR TITLE
Add an extension to negotiate use of post-handshake client auth

### PR DESCRIPTION
**Pull request by martinthomson**
As discussed in Chicago.

### CODE REVIEW

**Comment by ekr** [comment]
Hmm... I don't think that the server needs to confirm this, that just seems duplicative. I'd rather just have the client offer and the server knows it can then send. @martinthomson, open to being persuaded otherwise.

**Comment by davidben** [comment]
One minor argument for echoing is the client knows whether it needs to stash the partial transcript, but that may not be compelling enough to bother here. (If we cared about that, it seems better to start the transcript off an exporter value or something...)

**Comment by kaduk** [comment]
I guess there's enough bits to be worked out relating to the semantics of post-handshake server auth (presenting additional certificates) that we don't want to try to shoehorn that into the same extension codepoint.
My instinct would also have been to have the server echo back the signal, but I don't think I can provide any additional concrete argument in support of that.

**Comment by ekr** [comment]
My argument against is: what happens if the client offers, the server refuses, and then requests in any case. Seems like another thing to go wrong.

**Comment by davidben** [comment]
That's true. We'd need to worry about clients tracking that bit and actually enforcing, whereas there's no particular need for it.

**Pull request closed without merging**
